In [1]:
import  numpy as np

In [2]:
DIM_OFERTA = 5
DIM_DEMANDA = 5

In [26]:
asignaciones = np.zeros((DIM_OFERTA,DIM_DEMANDA))
asignaciones

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
of_arr = np.asanyarray([[1,2,3,4,5]]).T
of_arr

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [17]:
dem_arr = np.asanyarray([[3,3,3,3,3]])
dem_arr

array([[3, 3, 3, 3, 3]])

In [28]:
i = 4
j = 0
asignaciones[i,j]=min(of_arr[i,0],dem_arr[0,j])
asignaciones

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [3., 0., 0., 0., 0.]])

In [284]:
EstadoTransporte(estado.demandas.shape[1], estado.ofertas.flatten(), estado.demandas.flatten(), estado.asignaciones).total_sin_asignar

15

In [330]:
class EstadoTransporte(object):
    def __init__(self, dim, ofertas, demandas,\
                      asignaciones=None, costos=None):
        """
            dim es la dimension de la matriz (debe ser cuadrada)
            ofertas y demandas deben ser listas
        """
        if sum(ofertas) != sum(demandas):
            raise NotImplementedError('Todavia no funciona para desbalances')
        
        self.dim = dim
        self.ofertas = np.asanyarray([ofertas]).T
        self.demandas = np.asanyarray([demandas])
        self.total_sin_asignar = sum(self.demandas[0])
        if asignaciones is None:
            self.asignaciones = np.zeros((dim,dim))
        else:
            self.asignaciones = asignaciones
        if costos is None:
            self.costos = np.ones((dim,dim))
        else:
            self.costos = costos
    def asignar(self, fil,col, cant):
        self.asignaciones[fil,col] = cant
        self.ofertas[fil,0] -= cant
        self.demandas[0,col] -= cant
        self.total_sin_asignar -= cant
    def of_dem_disponibles(self):
        """
        devuelve indicesofertas_disp, indices_demandas_disp
        """
        ixs_ofertas_disp = np.where(~(estado.ofertas==0))[0] 
        ixs_demandas_disp = np.where(~(estado.demandas==0))[1]
        return ixs_ofertas_disp, ixs_demandas_disp
    def disponibles(self, ret_generator =True):
        f,c = self.of_dem_disponibles()
        if not ret_generator:
            return np.array(np.meshgrid(f,c)).T.reshape(-1,2)
        else: #dudo que yield ayude en algo, pues igual se crea la matriz
            for pos in np.array(np.meshgrid(f,c)).T.reshape(-1,2):
                yield pos
    def acciones_posibles(self):
        f,c = self.of_dem_disponibles()
        for x,y in np.array(np.meshgrid(f,c)).T.reshape(-1,2):
            yield x,y,min(self.ofertas[x,0], self.demandas[0,y])
    @classmethod
    def copiar(cls, obj):
        return cls(obj.demandas.shape[1],\
                   np.copy(obj.ofertas.flatten()),\
                   np.copy(obj.demandas.flatten()),\
                   np.copy(obj.asignaciones))
    
    def __repr__(self):
        s = ''
        s += ' '*len('(array([0]), array') + np.array2string(estado.demandas.astype(float),separator=', ') + '\n'
        s += '\n'.join([str(x) for x in zip(estado.ofertas,estado.asignaciones)])
        return s
    
    def __hash__(self):
        return hash(estado.asignaciones.tobytes())
    def __eq__(self, other):
        return self.__class__ == other.__class__ and\
               np.array_equal(self.asignaciones, other.asignaciones)

In [256]:
estado.asignaciones.tobytes()==estado2.asignaciones.tobytes()

True

In [191]:
[k for k in estado.disponibles()]

[array([2, 1], dtype=int32),
 array([2, 2], dtype=int32),
 array([2, 3], dtype=int32),
 array([2, 4], dtype=int32),
 array([3, 1], dtype=int32),
 array([3, 2], dtype=int32),
 array([3, 3], dtype=int32),
 array([3, 4], dtype=int32),
 array([4, 1], dtype=int32),
 array([4, 2], dtype=int32),
 array([4, 3], dtype=int32),
 array([4, 4], dtype=int32)]

In [331]:
estado = EstadoTransporte(5,[1,2,3,4,5],[3,3,3,3,3])

In [332]:
cop = EstadoTransporte.copiar(estado)

In [341]:
cop.asignar(0,0,1)

In [344]:
cop.total_sin_asignar

13

In [342]:
cop

                  [[3., 3., 3., 3., 3.]]
(array([1]), array([0., 0., 0., 0., 0.]))
(array([2]), array([0., 0., 0., 0., 0.]))
(array([3]), array([0., 0., 0., 0., 0.]))
(array([4]), array([0., 0., 0., 0., 0.]))
(array([5]), array([0., 0., 0., 0., 0.]))

In [343]:
estado.total_sin_asignar

15

In [336]:
estado

                  [[3., 3., 3., 3., 3.]]
(array([1]), array([0., 0., 0., 0., 0.]))
(array([2]), array([0., 0., 0., 0., 0.]))
(array([3]), array([0., 0., 0., 0., 0.]))
(array([4]), array([0., 0., 0., 0., 0.]))
(array([5]), array([0., 0., 0., 0., 0.]))

In [319]:
estado.asignaciones

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [312]:
estado2 = EstadoTransporte(5,[1,2,3,4,5],[3,3,3,3,3])

In [313]:
estado == estado2

True

In [316]:
estado.demandas

array([[3, 3, 3, 3, 3]])

In [268]:
d = dict()

In [271]:
d[estado2] = 2

In [272]:
d

{                  [[3., 3., 3., 3., 3.]]
 (array([1]), array([0., 0., 0., 0., 0.]))
 (array([2]), array([0., 0., 0., 0., 0.]))
 (array([3]), array([0., 0., 0., 0., 0.]))
 (array([4]), array([0., 0., 0., 0., 0.]))
 (array([5]), array([0., 0., 0., 0., 0.])): 2}

In [202]:
estado

                  [[3., 3., 3., 3., 3.]]
(array([1]), array([0., 0., 0., 0., 0.]))
(array([2]), array([0., 0., 0., 0., 0.]))
(array([3]), array([0., 0., 0., 0., 0.]))
(array([4]), array([0., 0., 0., 0., 0.]))
(array([5]), array([0., 0., 0., 0., 0.]))

In [208]:
estado.total_sin_asignar

12

In [204]:
estado.disponibles()

<generator object EstadoTransporte.disponibles at 0x0B31A8F0>

In [179]:
[k for k in estado.acciones_posibles()]

[(0, 0, 1),
 (0, 1, 1),
 (0, 2, 1),
 (0, 3, 1),
 (0, 4, 1),
 (1, 0, 2),
 (1, 1, 2),
 (1, 2, 2),
 (1, 3, 2),
 (1, 4, 2),
 (2, 0, 3),
 (2, 1, 3),
 (2, 2, 3),
 (2, 3, 3),
 (2, 4, 3),
 (3, 0, 3),
 (3, 1, 3),
 (3, 2, 3),
 (3, 3, 3),
 (3, 4, 3),
 (4, 0, 3),
 (4, 1, 3),
 (4, 2, 3),
 (4, 3, 3),
 (4, 4, 3)]

In [205]:
estado.asignar(0,0,1)

In [159]:
estado

                  [[2., 3., 3., 3., 3.]]
(array([0]), array([1., 0., 0., 0., 0.]))
(array([2]), array([0., 0., 0., 0., 0.]))
(array([3]), array([0., 0., 0., 0., 0.]))
(array([4]), array([0., 0., 0., 0., 0.]))
(array([5]), array([0., 0., 0., 0., 0.]))

In [207]:
estado.asignar(1,0,2)

In [227]:
estado

                  [[0., 3., 3., 3., 3.]]
(array([0]), array([1., 0., 0., 0., 0.]))
(array([0]), array([2., 0., 0., 0., 0.]))
(array([3]), array([0., 0., 0., 0., 0.]))
(array([4]), array([0., 0., 0., 0., 0.]))
(array([5]), array([0., 0., 0., 0., 0.]))

In [229]:
{estado}

{                  [[0., 3., 3., 3., 3.]]
 (array([0]), array([1., 0., 0., 0., 0.]))
 (array([0]), array([2., 0., 0., 0., 0.]))
 (array([3]), array([0., 0., 0., 0., 0.]))
 (array([4]), array([0., 0., 0., 0., 0.]))
 (array([5]), array([0., 0., 0., 0., 0.]))}

In [209]:
from notebook import psource
from search import Problem

In [210]:
psource(Problem)

In [211]:
estado.asignaciones

array([[1., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
class Iop2Problem(Problem):
    def actions(self, state):
        for accion in state.acciones_posibles():
            yield accion
    def result(self, state, action):
        
        
    
    def goal_test(self, state):
        return state.total_sin_asignar <= 0